In [33]:
import pandas as pd

In [34]:
data=pd.read_csv('dastasets/visitor-interests.csv')

In [35]:
data=data[:51]

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   IP         51 non-null     object
 1   UserAgent  51 non-null     object
 2   Country    51 non-null     object
 3   Languages  51 non-null     object
 4   Interests  51 non-null     object
dtypes: object(5)
memory usage: 2.1+ KB

In [37]:
data.head()

,IP,UserAgent,Country,Languages,Interests
0,1.10.195.126,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,TH,english,other
1,1.1.217.211,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,TH,thai,blog/personal homepage
2,1.115.198.107,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,JP,english,shop/online shopping website
3,1.121.152.143,Mozilla/5.0 (Linux; Android 7.0; Nexus 9 Build...,AU,english,company
4,1.123.135.213,Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X)...,AU,english,company

In [38]:
import user_agents 
def extract(ua):
    ua=user_agents.parse(ua)
    return pd.Series((ua.os.family,ua.browser.family,ua.device.family))
data[['os','browser','device']]=data['UserAgent'].apply(extract)
data.head()

,IP,UserAgent,Country,Languages,Interests,os,browser,device
0,1.10.195.126,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,TH,english,other,Windows,Chrome,Other
1,1.1.217.211,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,TH,thai,blog/personal homepage,Windows,Chrome,Other
2,1.115.198.107,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,JP,english,shop/online shopping website,Windows,Chrome,Other
3,1.121.152.143,Mozilla/5.0 (Linux; Android 7.0; Nexus 9 Build...,AU,english,company,Android,Chrome,Nexus 9
4,1.123.135.213,Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X)...,AU,english,company,iOS,Mobile Safari,iPad

In [43]:
data=data[:51]
from ip2geotools.databases.noncommercial import DbIpCity as ip2geo
def Ip_extract(ip):
    try:   
        ip=ip2geo.get(ip,api_key='free')
        return pd.Series((ip.latitude,ip.longitude))

    except:
        return 'missing'

data[['latitude','longitude']]=data['IP'].apply(Ip_extract)
data.head()

,IP,UserAgent,Country,Languages,Interests,os,browser,device,latitude,longitude
0,1.10.195.126,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,TH,english,other,Windows,Chrome,Other,NaN,NaN
1,1.1.217.211,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,TH,thai,blog/personal homepage,Windows,Chrome,Other,NaN,NaN
2,1.115.198.107,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,JP,english,shop/online shopping website,Windows,Chrome,Other,35.643227,139.740055
3,1.121.152.143,Mozilla/5.0 (Linux; Android 7.0; Nexus 9 Build...,AU,english,company,Android,Chrome,Nexus 9,-34.933411,138.600623
4,1.123.135.213,Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X)...,AU,english,company,iOS,Mobile Safari,iPad,-33.854816,151.216454